name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

env:
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v5
        with:
          version: 10
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build
        run: pnpm run build
